# This is a GitHub Actions workflow configuration file named "Hello world workflow".
# It is triggered on push and pull request events to the 'main' branch, and can also be manually triggered using the workflow_dispatch event.

# The workflow defines two jobs: 'hello' and 'goodbye'.
# Both jobs run on the latest version of Ubuntu.

# The 'hello' job:
# - Checks out the repository using the actions/checkout@v2 action.
# - Runs a step named "Hello world" that prints "Hello, world!" to the console using bash.

# The 'goodbye' job:
# - Checks out the repository using the actions/checkout@v2 action.
# - Runs a step named "Goodbye world" that prints "Goodbye, world!" to the console using bash.

# name: Hello world workflow

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   hello:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Hello world
#         run: echo Hello, world!
#         shell: bash
    
#   goodbye:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Goodbye world
#         run: echo Goodbye, world!
#         shell: bash

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: my-node-app

      - name: Run tests
        run: npm test
        working-directory: my-node-app 

      - name: Build Docker image
        run: docker build -t my-node-app .
        working-directory: my-node-app
